language: objective-c
osx_image: xcode9.2
script:
  - fastlane scan -p ThumbnailService/ThumbnailService.xcodeproj --scheme "ThumbnailService"

after_success:
  - bash <(curl -s https://codecov.io/bash)
